"""create bills, bill_items, and payments tables

Revision ID: 5aa22c99753f
Revises: c9b01a91562b
Create Date: 2026-08-13 16:49:26.309320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa22c99753f'
down_revision: Union[str, Sequence[str], None] = 'c9b01a91562b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Bill numbers are allocated from a dedicated sequence (database-design.md §5).
    op.execute("CREATE SEQUENCE bill_number_seq START 1")
    op.create_table('bills',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('bill_number', sa.String(length=20), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('appointment_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'REFUNDED')", name='ck_bills_status'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id'),
    sa.UniqueConstraint('bill_number')
    )
    op.create_index('idx_bills_appointment', 'bills', ['appointment_id'], unique=False)
    op.create_index('idx_bills_patient', 'bills', ['patient_id'], unique=False)
    op.create_index('idx_bills_status', 'bills', ['status'], unique=False)
    op.create_table('bill_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('bill_id', sa.BigInteger(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint("category IN ('CONSULTATION', 'LAB_TEST', 'PROCEDURE', 'SERVICE')", name='ck_bill_items_category'),
    sa.CheckConstraint('quantity > 0', name='ck_bill_items_quantity'),
    sa.CheckConstraint('unit_price >= 0', name='ck_bill_items_unit_price'),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bill_items_bill', 'bill_items', ['bill_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('bill_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_by', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("method IN ('CASH', 'CARD', 'UPI', 'BANK_TRANSFER', 'OTHER')", name='ck_payments_method'),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount'),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payments_bill', 'payments', ['bill_id'], unique=False)
    op.create_index('uq_payments_transaction_reference', 'payments', ['transaction_reference'], unique=True, postgresql_where=sa.text('transaction_reference IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_payments_transaction_reference', table_name='payments', postgresql_where=sa.text('transaction_reference IS NOT NULL'))
    op.drop_index('idx_payments_bill', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_bill_items_bill', table_name='bill_items')
    op.drop_table('bill_items')
    op.drop_index('idx_bills_status', table_name='bills')
    op.drop_index('idx_bills_patient', table_name='bills')
    op.drop_index('idx_bills_appointment', table_name='bills')
    op.drop_table('bills')
    op.execute("DROP SEQUENCE bill_number_seq")
    # ### end Alembic commands ###
