"""create prescriptions, prescription_items, and patient_allergies tables

Revision ID: 90cbc46f5896
Revises: ec6d2fd8aee4
Create Date: 2026-08-13 16:20:31.775123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90cbc46f5896'
down_revision: Union[str, Sequence[str], None] = 'ec6d2fd8aee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_allergies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('allergen', sa.String(length=150), nullable=False),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('MILD', 'MODERATE', 'SEVERE')", name='ck_patient_allergies_severity'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_patient_allergies_patient', 'patient_allergies', ['patient_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('medical_record_id', sa.BigInteger(), nullable=False),
    sa.Column('doctor_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['medical_record_id'], ['medical_records.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prescriptions_doctor', 'prescriptions', ['doctor_id'], unique=False)
    op.create_index('idx_prescriptions_patient', 'prescriptions', ['patient_id'], unique=False)
    op.create_index('idx_prescriptions_record', 'prescriptions', ['medical_record_id'], unique=False)
    op.create_table('prescription_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('prescription_id', sa.BigInteger(), nullable=False),
    sa.Column('medicine_name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration_in_days', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('duration_in_days > 0', name='ck_prescription_items_duration_in_days'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prescription_items_prescription', 'prescription_items', ['prescription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prescription_items_prescription', table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index('idx_prescriptions_record', table_name='prescriptions')
    op.drop_index('idx_prescriptions_patient', table_name='prescriptions')
    op.drop_index('idx_prescriptions_doctor', table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index('idx_patient_allergies_patient', table_name='patient_allergies')
    op.drop_table('patient_allergies')
    # ### end Alembic commands ###
