"""add rate_limit_events table

Revision ID: a0b12639a607
Revises: 7a18c2d94e5b
Create Date: 2026-08-17 15:19:41.889482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b12639a607'
down_revision: Union[str, Sequence[str], None] = '7a18c2d94e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'key_hash', 'window_start', name='uq_rate_limit_events_scope_key_window')
    )
    op.create_index('idx_rate_limit_lookup', 'rate_limit_events', ['scope', 'key_hash', 'window_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rate_limit_lookup', table_name='rate_limit_events')
    op.drop_table('rate_limit_events')
    # ### end Alembic commands ###
