"""create lab_requests table

Revision ID: a4d90cacb8d5
Revises: 90cbc46f5896
Create Date: 2026-08-13 16:30:01.770759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d90cacb8d5'
down_revision: Union[str, Sequence[str], None] = '90cbc46f5896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('appointment_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('doctor_id', sa.BigInteger(), nullable=False),
    sa.Column('test_name', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'REQUESTED'"), nullable=False),
    sa.Column('result_details', sa.Text(), nullable=True),
    sa.Column('report_file_path', sa.String(length=500), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_by', sa.BigInteger(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('REQUESTED', 'IN_PROGRESS', 'RESULT_READY', 'VERIFIED')", name='ck_lab_requests_status'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lab_appointment', 'lab_requests', ['appointment_id'], unique=False)
    op.create_index('idx_lab_doctor', 'lab_requests', ['doctor_id'], unique=False)
    op.create_index('idx_lab_patient', 'lab_requests', ['patient_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_lab_patient', table_name='lab_requests')
    op.drop_index('idx_lab_doctor', table_name='lab_requests')
    op.drop_index('idx_lab_appointment', table_name='lab_requests')
    op.drop_table('lab_requests')
    # ### end Alembic commands ###
