"""add verified_by_admin to lab_requests

Revision ID: c9b01a91562b
Revises: a4d90cacb8d5
Create Date: 2026-08-13 16:36:51.504865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b01a91562b'
down_revision: Union[str, Sequence[str], None] = 'a4d90cacb8d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_requests', sa.Column('verified_by_admin', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_lab_requests_verified_by_admin', 'lab_requests', 'users', ['verified_by_admin'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_lab_requests_verified_by_admin', 'lab_requests', type_='foreignkey')
    op.drop_column('lab_requests', 'verified_by_admin')
    # ### end Alembic commands ###
