"""add doctor_schedules and doctor_unavailable

Revision ID: df3d4c3f4d8c
Revises: 5d95eaf63c94
Create Date: 2026-08-13 19:38:56.634628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3d4c3f4d8c'
down_revision: Union[str, Sequence[str], None] = '5d95eaf63c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_schedules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('doctor_id', sa.BigInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='ck_doctor_schedules_day_of_week'),
    sa.CheckConstraint('end_time > start_time', name='ck_doctor_schedules_time_range'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'day_of_week', 'start_time', name='uq_doctor_schedules_doctor_day_start')
    )
    op.create_index('idx_doctor_schedules_doctor', 'doctor_schedules', ['doctor_id'], unique=False)
    op.create_table('doctor_unavailable',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('doctor_id', sa.BigInteger(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('to_date >= from_date', name='ck_doctor_unavailable_date_range'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_unavail_doctor', 'doctor_unavailable', ['doctor_id', 'from_date', 'to_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_doc_unavail_doctor', table_name='doctor_unavailable')
    op.drop_table('doctor_unavailable')
    op.drop_index('idx_doctor_schedules_doctor', table_name='doctor_schedules')
    op.drop_table('doctor_schedules')
    # ### end Alembic commands ###
