"""create patients table

Revision ID: f9af0daae231
Revises: 9648ec3a7d00
Create Date: 2026-08-12 19:41:11.979216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9af0daae231'
down_revision: Union[str, Sequence[str], None] = '9648ec3a7d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('mrn', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('blood_group', sa.Text(), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("blood_group IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', 'UNKNOWN')", name='ck_patients_blood_group'),
    sa.CheckConstraint("gender IN ('MALE', 'FEMALE', 'OTHER')", name='ck_patients_gender'),
    sa.CheckConstraint('dob <= CURRENT_DATE', name='ck_patients_dob'),
    sa.CheckConstraint('height_cm > 0 AND height_cm < 300', name='ck_patients_height_cm'),
    sa.CheckConstraint('weight_kg > 0 AND weight_kg < 500', name='ck_patients_weight_kg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mrn'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_patients_name', 'patients', ['last_name', 'first_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_patients_name', table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
